import 'package:flutter/material.dart';

import 'categories_box.dart';

class RightSideOfSite extends StatelessWidget {
  const RightSideOfSite({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Container(
          margin: const EdgeInsets.only(top: 8),
          width: 275,
          height: 80,
          decoration: const BoxDecoration(
              image: DecorationImage(
                  fit: BoxFit.cover,
                  image: AssetImage('assets/images/tele.png'))),
        ),
        const CategoryBox(
          title: 'تفکیک سال انتشار',
          icon: Icons.local_movies_outlined,
          visible: true,
          height: 2830,
          texts: [
            '1921',
            '1930',
            '1931',
            '1932',
            '1933',
            '1934',
            '1935',
            '1936',
            '1937',
            '1938',
            '1939',
            '1940',
            '1941',
            '1942',
            '1944',
            '1946',
            '1947',
            '1948',
            '1949',
            '1950',
            '1951',
            '1953',
            '1954',
            '1955',
            '1956',
            '1957',
            '1958',
            '1959',
            '1960',
            '1961',
            '1962',
            '1963',
            '1964',
            '1965',
            '1966',
            '1967',
            '1968',
            '1969',
            '1970',
            '1971',
            '1972',
            '1973',
            '1974',
            '1975',
            '1976',
            '1977',
            '1978',
            '1979',
            '1980',
            '1981',
            '1982',
            '1983',
            '1984',
            '1985',
            '1986',
            '1987',
            '1988',
            '1989',
            '1990',
            '1991',
            '1992',
            '1993',
            '1994',
            '1995',
            '1996',
            '1997',
            '1998',
            '1999',
            '2000',
            '2001',
            '2002',
            '2003',
            '2004',
            '2005',
            '2006',
            '2007',
            '2008',
            '2009',
            '2010',
            '2011',
            '2012',
            '2013',
            '2014',
            '2015',
            '2016',
            '2017',
            '2018',
            '2019',
            '2020',
            '2021',
            '2022',
            '2023',
            '2024',
          ],
        ),
        const CategoryBox(
            title: 'تفکیک کیفیت',
            icon: Icons.local_movies_outlined,
            visible: true,
            height: 800,
            texts: [
              '۱۰۸۰p HDRip',
              '۱۰۸۰p WEB-DL',
              '۱۰۸۰p WEB-DL Full HD',
              '۱۰۸۰p WEBRip',
              '۳D',
              '۴۸۰p HDTV',
              '۴K 2160p',
              '۷۲۰p DVDRip',
              '۷۲۰p HDRip',
              '۷۲۰p HDTV',
              '۷۲۰p WEB-DL',
              '۷۲۰p WEBRip',
              'BDRip',
              ' Bluray 1080p',
              '  Bluray 1080p Full HD',
              '   Bluray 480p',
              'Bluray 720p',
              'DVDRip',
              'DVDSCR',
              'HDCam',
              'HDRip',
              'HDTV',
              'Mobile',
              'TS',
              'WEBRip',
              'x265',
            ]),
        const CategoryBox(
            title: 'تفکیک ژانر',
            icon: Icons.local_movies_outlined,
            visible: true,
            height: 860,
            texts: [
              'اجتماعی',
              'اکشن',
              'انیمیشن',
              'بیوگرافی',
              'تاریخی',
              'ترسناک',
              'جنایی',
              'جنگی',
              'خانوادگی',
              'درام',
              'رئالیتی شو',
              'رازآلود',
              'رزمی',
              'علمی تخیلی',
              'غم انگیز',
              'فانتزی',
              'فیلم نوآر',
              'کمدی',
              'کوتاه',
              'ماجراجویی',
              'مراسم',
              'مستند',
              'معمایی',
              'موزیکال',
              'موسیقی',
              'هیجانی',
              'ورزشی',
              'وسترن',
            ]),
        const CategoryBox(
            title: 'کالکشن',
            icon: Icons.local_movies_outlined,
            texts: [
              'Ace Ventura',
              'Against The Wild',
              'Alice in Wonderland',
              'Alien',
              'Alien Vs. Predator',
              'Almighty',
              'Along With The Gods',
              'Alvin And The Chipmunks',
              'An Inconvenient Truth',
              'Anchorman',
              'Angry Birds',
              'Annabelle',
              'Ant-Man',
              'Antboy',
              ' Attack On Titan',
              ' Avengers',
              'Back To The Future',
              'Backdraft',
              'Bad Boys',
              'Batman',
              'Belle And Sebastian',
              'Best Friends',
              'Beverly Hills Cop',
              'Blade',
              'Born To Race',
              'Brother Bear',
              'Brotherhood Of Blades',
              'Captain America',
              'Cars',
              'Cats And Dogs',
              'Cloudy With A Chance Of Meatballs',
              'Cloverfield',
              'Coconut The Little Dragon',
              'Cold War',
              'Creed',
              'Cub',
              'Daddys Home',
              'Dead Snow',
              'Deadpool',
              'Despicable Me',
              'Detective Dee',
              'Dhoom',
              ' Diary Of A Wimpy Kid',
              ' Die Hard',
              'District 13',
              ' Doctor Dolittle',
              'Dolphin Tale',
              ' Don',
              ' Dragon Ball Z',
              ' Dumb And Dumber',
              'Easy Money',
              'Escape Plan',
              'Fantastic Beasts',
              'Fantastic Four',
              'Fast And Furious',
              'Final Destination',
              'Frozen',
              'G.I. Joe',
              'Garfield',
              'Generation Iron',
              'Ghost Rider',
              'Ghostbusters',
              'Gintama',
              'Godzilla',
              'Gogol',
              'Goosebumps',
              'Grown Ups',
              'Guardians Of The Galaxy',
              'Happy Death Day',
              ' Happy Feet',
              ' Harry Potter',
              ' Hellboy',
              'Hitman',
              ' Home Alone',
              ' Hoodwinked',
              ' Horrible Bosses',
              ' Hotel Transylvania',
              ' How To Train Your Dragon',
              ' Hulk',
              'Ice Age',
              'Iceman',
              'Incredibles',
              'Independence Day',
              'Indiana Jones',
              'Inside Out',
              'Insidious',
              'Ip Man',
              'Iron Man',
              'Iron Sky',
              'Ironclad',
              'It',
              'Jeepers Creepers',
              'Jingle All The Way',
              'Johan Falk',
              'John Wick',
              'Johnny English',
              'Journey',
              'Jumanji',
              'Jump Street',
              'Jurassic Park',
              'Kickboxer',
              'Kill Bill',
              'Kingsman',
              ' Kung Fu Panda',
              ' Lazer Team',
              ' Mad Max',
              ' Madagascar',
              ' March Of The Penguins',
              ' Maze Runner',
              'Men in Black',
              'Mission Impossible',
              'Monster Hunt',
              ' Monsters',
              ' Monsters Inc',
              ' Muppets',
              ' Mythica',
              ' Nanny McPhee',
              ' National Treasure',
              ' Night At The Museum',
              'Ninja Turtles',
              ' Norm Of The North',
              'Now You See Me',
              'Oceans',
              ' Ong-Bak',
              ' Open Season',
              'Outpost',
              ' Outrage',
              ' Overheard',
              'Pacific Rim',
              'Paddington',
              'Paranormal Activity',
              'Paul Blart : Mall Cop',
              'Percy Jackson',
              'Pirates Of The Caribbean',
              'Planes',
              'Police Story',
              'Predator',
              'Puss in Boots',
              'Queen Of Spades',
              'Rambo',
              'Rampage',
              'RED',
              'Red Cliff',
              'Red Dog',
              'Ride Along',
              'Rocky',
              'Rurouni Kenshin',
              'Rush Hour',
              'Saints And Soldiers',
              'Shaft',
              'Shanghai',
              'Sheep And Wolves',
              'Sherlock Holmes',
              'Shrek',
              'Sicario',
              'Silent Hill',
              'Sin',
              'Singham',
              'Sinister',
              'Snow White And The Huntsman',
              'Snowtime',
              'Spider Man',
              'Star Trek',
              'Star Wars',
              'Starship',
              'Taken',
              'Tangled',
              'Taxi',
              'Terminator',
              'The Bourne',
              'The Chronicles Of Narnia',
              'The Condemned',
              'The Conjuring',
              'The Croods',
              'The Dead',
              'The Divergent Series',
            ],
            height: 5300,
            visible: true),
        const CategoryBox(
            title: '۲۵۰ فیلم برتر',
            icon: Icons.local_movies_outlined,
            texts: ['۲۵۰ فیلم برتر'],
            height: 50,
            visible: true),
        const CategoryBox(
            title: 'فیلم ایرانی',
            icon: Icons.local_movies_outlined,
            texts: ['دانلود فیلم ایرانی'],
            height: 50,
            visible: true),
        const CategoryBox(
            title: 'فیلم دوبله فارسی',
            icon: Icons.local_movies_outlined,
            texts: ['فیلم دوبله فارسی'],
            height: 50,
            visible: true),
      ],
    );
  }
}
